//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlAssignment1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using SourceControlAssignment1.Models;

    public partial class tbl_registration
    {
        [Key]
        public int UserId { get; set; }
        [Required(ErrorMessage="Please Enter Name")]
       [CustomValidation1("@!?_{}<>*&^%$#.")]
        public string Name { get; set; }
        [StringLength(60, MinimumLength = 20)]
        [Required]
        public string Address { get; set; }
        [Required]
        [DisplayName("Date Of Birth")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required(ErrorMessage ="Please Enter EmailId")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please Enter Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        [DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Please Enter Phone no.")]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Contact no.")]
        public string Phone { get; set; }
    }
    
    public class UserDbContext : DbContext
    {
        public DbSet<tbl_registration> Users { get; set; }
    }
    
}
